export const sidebar = [
    {
        id: 1,
        title: 'Buttons',
        path: '/buttons',
        Element: '',
        private: false,
    },
    {
        id: 2,
        title: 'Inputs',
        path: '/inputs',
        Element: '',
        private: false,
    },
    {
        id: 3,
        title: 'Dropdown',
        path: '/dropdown',
        Element: '',
        private: false,
    },
    {
        id: 4,
        title: 'Tooltip',
        path: '/tooltip',
        Element: '',
        private: false,
    },
    {
        id: 5,
        title: 'Menu',
        path: '/menu',
        Element: '',
        private: false,
    },
    {
        id: 6,
        title: 'Steps',
        path: '/steps',
        Element: '',
        private: false,
    },
    {
        id: 7,
        title: 'Calendar',
        path: '/calendar',
        Element: '',
        private: false,
    },
    {
        id: 8,
        title: 'Maps',
        path: '/maps',
        Element: '',
        private: false,
    },
    {
        id: 9,
        title: 'Charts',
        path: '/charts',
        Element: '',
        private: false,
    },
    {
        id: 10,
        title: 'Checkbox',
        path: '/checkbox',
        Element: '',
        private: false,
    },
    {
        id: 11,
        title: 'Forms',
        path: '/forms',
        Element: '',
        private: false,
    },
    {
        id: 12,
        title: 'DatePicker',
        path: '/datePicker',
        Element: '',
        private: false,
    },
    {
        id: 13,
        title: 'Switch',
        path: '/switch',
        Element: '',
        private: false,
    },
    {
        id: 14,
        title: 'Transfer',
        path: '/transfer',
        Element: '',
        private: false,
    },
    {
        id: 15,
        title: 'Upload',
        path: '/upload',
        Element: '',
        private: false,
    },
    {
        id: 16,
        title: 'Avatar',
        path: '/avatar',
        Element: '',
        private: false,
    },
    {
        id: 17,
        title: 'Badge',
        path: '/badge',
        Element: '',
        private: false,
    },
    {
        id: 18,
        title: 'Card',
        path: '/card',
        Element: '',
        private: false,
    },
    {
        id: 19,
        title: 'Carousel',
        path: '/carousel',
        Element: '',
        private: false,
    },
    {
        id: 20,
        title: 'Collapse',
        path: '/collapse',
        Element: '',
        private: false,
    },
    {
        id: 21,
        title: 'Image',
        path: '/image',
        Element: '',
        private: false,
    },
    {
        id: 22,
        title: 'Pagination',
        path: '/pagination',
        Element: '',
        private: false,
    },
    {
        id: 23,
        title: 'Popover',
        path: '/popover',
        Element: '',
        private: false,
    },
    {
        id: 24,
        title: 'Table',
        path: '/table',
        Element: '',
        private: false,
    },
    {
        id: 25,
        title: 'Tabs',
        path: '/tabs',
        Element: '',
        private: false,
    },
    {
        id: 26,
        title: 'Alert',
        path: '/alert',
        Element: '',
        private: false,
    },
    {
        id: 27,
        title: 'Drawer',
        path: '/drawer',
        Element: '',
        private: false,
    },
    {
        id: 28,
        title: 'Modal',
        path: '/modal',
        Element: '',
        private: false,
    },
    {
        id: 29,
        title: 'Notification',
        path: '/notification',
        Element: '',
        private: false,
    },
    {
        id: 30,
        title: 'PopConfirm',
        path: '/popConfirm',
        Element: '',
        private: false,
    },
    {
        id: 31,
        title: 'Progress',
        path: '/progress',
        Element: '',
        private: false,
    },
    {
        id: 32,
        title: 'Result',
        path: '/result',
        Element: '',
        private: false,
    },
    {
        id: 33,
        title: 'Spinner',
        path: '/spinner',
        Element: '',
        private: false,
    },
] 